-- AlterTable
ALTER TABLE "User" DROP COLUMN IF EXISTS "hasCompletedOnboarding";
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "onboardingCompleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "onboardingStep" INTEGER DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "onboardingSkipped" BOOLEAN NOT NULL DEFAULT false;
